name: remedi
description: "A medical reminder application."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  logger: ^1.0.0
  drift: ^2.8.0
  drift_flutter: ^0.2.7
  path_provider: ^2.0.0
  json_annotation: ^4.0.1
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  drift_dev: ^2.8.0
  flutter_launcher_icons: ^0.13.1

# ðŸ”½ THIS MUST BE OUTSIDE dev_dependencies
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/remedi_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
